name: Build

on: [push, pull_request]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build -x lint 
    - name: Copy Release Artifacts
      run: |
        mkdir geopackage-sdk/build/release
        cp geopackage-sdk/build/libs/*.jar geopackage-sdk/build/outputs/aar/*release.aar geopackage-sdk/build/release/
        grep "version =" geopackage-sdk/build.gradle | sed 's/[a-z ="]//g' > VERSION
        mv geopackage-sdk/build/release/*.aar geopackage-sdk/build/release/geopackage-android-$(cat VERSION).aar 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: geopackage-android
        path: geopackage-sdk/build/release
